---
- name: Include OS Specific setup tasks
  import_tasks: setup-{{ ansible_os_family }}.yml

- import_tasks: config.yml
- import_tasks: ssl.yml
- import_tasks: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
